### PR TITLE
add dh.data

### PR DESCRIPTION
**Pull request by viky600833**
s.load.t&&google.tick&&google.tick("load",{gen204:"xjsls",clearcut:31});document.getElementById("xjsd").appendChild(a)},0)}google.dljp=function(b,a){google.xjsu=b;c(a)};google.dlj=c;}).call(this);if(!google.xjs){window._=window._||{};window._DumpException=window._._DumpException=function(e){throw e};window._F_installCss=window._._F_installCss=function(c){};google.dljp('/xjs/_/js/k\x3dxjs.hp.en.5LrXty7tLds.O/m\x3dsb_he,d/am\x3dYsAs/rt\x3dj/d\x3d1/rs\x3dACT90oEgmKTJpJXV88Q715FsVyLLA9gg7g','/xjs/_/js/k\x3dxjs.hp.en.5LrXty7tLds.O/m\x3dsb_he,d/am\x3dYsAs/rt\x3dj/d\x3d1/rs\x3dACT90oEgmKTJpJXV88Q715FsVyLLA9gg7g');google.xjs=1;}google.pmc={"sb_he":{"agen":true,"cgen":true,"client":"heirloom-hp","dh":true,"dhqt":true,"ds":"","ffql":"fr","fl":true,"host":"google.fr","isbh":28,"jsonp":true,"lm":true,"msgs":{"cibl":"Effacer la recherche","dym":"Essayez avec cette orthographe :","lcky":"J\u0026#39;ai de la chance","lml":"En savoir plus","oskt":"Outils de saisie","psrc":"Cette suggestion a bien ▒t▒ supprim▒e de votre \u003Ca href=\"/history\"\u003Ehistorique Web\u003C/a\u003E.","psrl":"Supprimer","sbit":"Recherche par image","srch":"Recherche Google"},"ovr":{},"pq":"","refpd":true,"rfs":[],"sbpl":24,"sbpr":24,"scd":10,"sce":5,"stok":"aHBo8UZRrQahIynB_IB8Z2b4K-A","uhde":false},"d":{},"ZI/YVQ":{},"Qnk92g":{},"U5B21g":{},"YFCs/g":{}};google.x(null,function(){});(function(){var r=[];google.plm(r);})();(function(){var m=[]
;m.length && google.jsc && google.jsc.m(m);})();</script></div></body></html>user1@ubuntu:~$
user1@ubuntu:~$
user1@ubuntu:~$
user1@ubuntu:~$
user1@ubuntu:~$
user1@ubuntu:~$ ls
ansible.cfg.bck   bck__init__.py  examples.desktop  __pycache__  test04.yml               workspace
bck.bash_profile  essai7.py       orig.checking.py  test02.yml   vault_password_file.txt
user1@ubuntu:~$ cd workspace/
user1@ubuntu:~/workspace$ ls
ansible.cfg  meta.py  README.txt  test01.yml  test03.yml  utils
user1@ubuntu:~/workspace$ mkdir git
user1@ubuntu:~/workspace$ cd git
user1@ubuntu:~/workspace/git$
user1@ubuntu:~/workspace/git$
user1@ubuntu:~/workspace/git$
user1@ubuntu:~/workspace/git$ ls
user1@ubuntu:~/workspace/git$ git clone https://github.com/600833/data_puppet_hiera.git data_puppet_hiera
Cloning into 'data_puppet_hiera'...
remote: Enumerating objects: 7, done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 7
Unpacking objects: 100% (7/7), done.
user1@ubuntu:~/workspace/git$ cd data_puppet_hiera/
user1@ubuntu:~/workspace/git/data_puppet_hiera$ ls
global.yaml  moduledata  nodedata
us

### CODE REVIEW

**Comment by 600833** [comment]
It's dh down fail

**Comment by viky600833** [comment]
I will try again

**Comment by viky600833** [comment]
I update dh.data

**Comment by 600833** [comment]
it seems ok i'll merge it

**Review by 600833 — APPROVED** [review]
it's 12KL run

**Comment by viky600833** [comment]
loc

**Pull request merged**
